Sudo: required
Services:
  - docker
before-install:
  - gem install bundler
  - docker build -t guptasunil2k/docker-react -f Dockerfile.dev .

Scripts:
  - docker run guptasunil2k/docker-react npm run test -- --coverage

