sudo: required
services:
  - docker
before_install:
  - gem install bundler
  - docker build -t guptasunil2k/docker-react -f Dockerfile.dev .

script:
  
  - docker run guptasunil2k/docker-react npm run test -- --coverage

